/**
 * Dhanya Jurisdictional & Regulatory Registry
 * Package: @dhanya/finance-engine
 * 
 * Verified statutory reference data for global jurisdictions, tax authorities, and benchmark sources.
 */

import {
  CountryInfo,
  CountryCode,
  SourceProvenance,
  TaxBracket,
  VersionedFinancialRule,
  WhatChangedEvent,
} from '@dhanya/types';

export const PROVENANCE_SOURCES: Record<string, SourceProvenance> = {
  FED: {
    id: 'src-fed-us',
    name: 'Federal Reserve System',
    organization: 'Board of Governors of the Federal Reserve',
    organizationType: 'CENTRAL_BANK',
    officialUrl: 'https://www.federalreserve.gov/monetarypolicy/openmarket.htm',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Actuarial Review Board',
    verificationStatus: 'VERIFIED',
    notes: 'Primary benchmark rate authority for US dollar lending models.',
  },
  IRS: {
    id: 'src-irs-us',
    name: 'Internal Revenue Service (IRS)',
    organization: 'United States Department of the Treasury',
    organizationType: 'TAX_AUTHORITY',
    officialUrl: 'https://www.irs.gov/newsroom/irs-releases-tax-inflation-adjustments-for-tax-year-2025',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Tax Research',
    verificationStatus: 'VERIFIED',
    notes: 'IRS Revenue Procedure 2024-40 (Tax Year 2025 brackets).',
  },
  BOC: {
    id: 'src-boc-ca',
    name: 'Bank of Canada',
    organization: 'Banque du Canada',
    organizationType: 'CENTRAL_BANK',
    officialUrl: 'https://www.bankofcanada.ca/core-functions/monetary-policy/key-interest-rate/',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Actuarial Review Board',
    verificationStatus: 'VERIFIED',
    notes: 'Policy interest rate and overnight rate target.',
  },
  CRA: {
    id: 'src-cra-ca',
    name: 'Canada Revenue Agency (CRA)',
    organization: 'Government of Canada',
    organizationType: 'TAX_AUTHORITY',
    officialUrl: 'https://www.canada.ca/en/revenue-agency/services/tax/individuals/frequently-asked-questions-individuals/canadian-income-tax-rates-individuals-current-previous-years.html',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Tax Research',
    verificationStatus: 'VERIFIED',
    notes: '2025 Canadian federal progressive tax brackets indexed to CPI (2.7% indexation factor).',
  },
  RBI: {
    id: 'src-rbi-in',
    name: 'Reserve Bank of India (RBI)',
    organization: 'Monetary Policy Committee (MPC)',
    organizationType: 'CENTRAL_BANK',
    officialUrl: 'https://rbi.org.in/scripts/BS_PressReleaseDisplay.aspx',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Actuarial Review Board',
    verificationStatus: 'VERIFIED',
    notes: 'Policy Repo Rate under Liquidity Adjustment Facility (LAF).',
  },
  ITD_IN: {
    id: 'src-itd-in',
    name: 'Income Tax Department of India',
    organization: 'Ministry of Finance, Government of India',
    organizationType: 'TAX_AUTHORITY',
    officialUrl: 'https://incometaxindia.gov.in/pages/charts-and-tables.aspx',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Tax Research',
    verificationStatus: 'VERIFIED',
    notes: 'Union Budget Finance Act Section 115BAC (New Tax Regime).',
  },
  BOE: {
    id: 'src-boe-gb',
    name: 'Bank of England',
    organization: 'Monetary Policy Committee (MPC)',
    organizationType: 'CENTRAL_BANK',
    officialUrl: 'https://www.bankofengland.co.uk/monetary-policy/the-interest-rate-bank-rate',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Actuarial Review Board',
    verificationStatus: 'VERIFIED',
    notes: 'Official Bank Rate decision.',
  },
  HMRC: {
    id: 'src-hmrc-gb',
    name: 'HM Revenue & Customs (HMRC)',
    organization: 'Government of the United Kingdom',
    organizationType: 'TAX_AUTHORITY',
    officialUrl: 'https://www.gov.uk/income-tax-rates',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Tax Research',
    verificationStatus: 'VERIFIED',
    notes: 'UK Income tax bands and Personal Allowance thresholds.',
  },
  RBA: {
    id: 'src-rba-au',
    name: 'Reserve Bank of Australia (RBA)',
    organization: 'Reserve Bank Board',
    organizationType: 'CENTRAL_BANK',
    officialUrl: 'https://www.rba.gov.au/monetary-policy/cash-rate-target.html',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Actuarial Review Board',
    verificationStatus: 'VERIFIED',
    notes: 'Cash Rate Target.',
  },
  ATO: {
    id: 'src-ato-au',
    name: 'Australian Taxation Office (ATO)',
    organization: 'Commonwealth of Australia',
    organizationType: 'TAX_AUTHORITY',
    officialUrl: 'https://www.ato.gov.au/tax-rates-and-codes/tax-rates-australian-residents',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Tax Research',
    verificationStatus: 'VERIFIED',
    notes: 'Stage 3 Tax Cuts amended rate schedule.',
  },
  MAS: {
    id: 'src-mas-sg',
    name: 'Monetary Authority of Singapore (MAS)',
    organization: 'Government of Singapore',
    organizationType: 'CENTRAL_BANK',
    officialUrl: 'https://www.mas.gov.sg/monetary-policy',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Actuarial Review Board',
    verificationStatus: 'VERIFIED',
    notes: 'SORA and Monetary Policy Framework.',
  },
  IRAS: {
    id: 'src-iras-sg',
    name: 'Inland Revenue Authority of Singapore (IRAS)',
    organization: 'Government of Singapore',
    organizationType: 'TAX_AUTHORITY',
    officialUrl: 'https://www.iras.gov.sg/taxes/individual-income-tax/basics-of-individual-income-tax/tax-rates-and-tax-reliefs/individual-income-tax-rates',
    lastVerifiedAt: '2025-03-01T00:00:00Z',
    verifiedBy: 'Dhanya Tax Research',
    verificationStatus: 'VERIFIED',
    notes: 'Singapore progressive resident individual income tax rates.',
  },
};

export const COUNTRIES: CountryInfo[] = [
  {
    code: 'US',
    name: 'United States',
    currency: { code: 'USD', symbol: '$', name: 'US Dollar', locale: 'en-US' },
    flag: '🇺🇸',
    centralBank: 'Federal Reserve (Fed)',
    taxAuthority: 'Internal Revenue Service (IRS)',
    defaultMortgageTermYears: 30,
    standardLoanCompounding: 'MONTHLY',
    jurisdictions: [
      { id: 'us-fed', countryCode: 'US', name: 'Federal (Single Filer)', type: 'FEDERAL', taxYear: '2025' },
      { id: 'us-ca', countryCode: 'US', name: 'California State', type: 'STATE', taxYear: '2025' },
      { id: 'us-ny', countryCode: 'US', name: 'New York State', type: 'STATE', taxYear: '2025' },
      { id: 'us-tx', countryCode: 'US', name: 'Texas (No State Income Tax)', type: 'STATE', taxYear: '2025' },
    ],
  },
  {
    code: 'CA',
    name: 'Canada',
    currency: { code: 'CAD', symbol: '$', name: 'Canadian Dollar', locale: 'en-CA' },
    flag: '🇨🇦',
    centralBank: 'Bank of Canada (BoC)',
    taxAuthority: 'Canada Revenue Agency (CRA)',
    defaultMortgageTermYears: 25,
    standardLoanCompounding: 'SEMI_ANNUAL', // Canadian standard semi-annual compounding
    jurisdictions: [
      { id: 'ca-fed', countryCode: 'CA', name: 'Federal', type: 'FEDERAL', taxYear: '2025' },
      { id: 'ca-on', countryCode: 'CA', name: 'Ontario', type: 'PROVINCE', taxYear: '2025' },
      { id: 'ca-bc', countryCode: 'CA', name: 'British Columbia', type: 'PROVINCE', taxYear: '2025' },
      { id: 'ca-ab', countryCode: 'CA', name: 'Alberta', type: 'PROVINCE', taxYear: '2025' },
    ],
  },
  {
    code: 'IN',
    name: 'India',
    currency: { code: 'INR', symbol: '₹', name: 'Indian Rupee', locale: 'en-IN' },
    flag: '🇮🇳',
    centralBank: 'Reserve Bank of India (RBI)',
    taxAuthority: 'Income Tax Department (ITD)',
    defaultMortgageTermYears: 20,
    standardLoanCompounding: 'MONTHLY',
    jurisdictions: [
      { id: 'in-new', countryCode: 'IN', name: 'New Tax Regime (Sec 115BAC)', type: 'FEDERAL', taxYear: '2025-26' },
      { id: 'in-old', countryCode: 'IN', name: 'Old Tax Regime (With Deductions)', type: 'FEDERAL', taxYear: '2025-26' },
    ],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    currency: { code: 'GBP', symbol: '£', name: 'British Pound', locale: 'en-GB' },
    flag: '🇬🇧',
    centralBank: 'Bank of England (BoE)',
    taxAuthority: 'HM Revenue & Customs (HMRC)',
    defaultMortgageTermYears: 25,
    standardLoanCompounding: 'DAILY',
    jurisdictions: [
      { id: 'gb-eng', countryCode: 'GB', name: 'England & Northern Ireland', type: 'FEDERAL', taxYear: '2024-25' },
      { id: 'gb-sct', countryCode: 'GB', name: 'Scotland', type: 'STATE', taxYear: '2024-25' },
    ],
  },
  {
    code: 'AU',
    name: 'Australia',
    currency: { code: 'AUD', symbol: '$', name: 'Australian Dollar', locale: 'en-AU' },
    flag: '🇦🇺',
    centralBank: 'Reserve Bank of Australia (RBA)',
    taxAuthority: 'Australian Taxation Office (ATO)',
    defaultMortgageTermYears: 30,
    standardLoanCompounding: 'MONTHLY',
    jurisdictions: [
      { id: 'au-fed', countryCode: 'AU', name: 'Federal (Stage 3 Rates)', type: 'FEDERAL', taxYear: '2024-25' },
    ],
  },
  {
    code: 'SG',
    name: 'Singapore',
    currency: { code: 'SGD', symbol: '$', name: 'Singapore Dollar', locale: 'en-SG' },
    flag: '🇸🇬',
    centralBank: 'Monetary Authority of Singapore (MAS)',
    taxAuthority: 'Inland Revenue Authority (IRAS)',
    defaultMortgageTermYears: 25,
    standardLoanCompounding: 'MONTHLY',
    jurisdictions: [
      { id: 'sg-res', countryCode: 'SG', name: 'Resident Individual Tax', type: 'FEDERAL', taxYear: '2024' },
    ],
  },
];

export const TAX_BRACKETS_BY_JURISDICTION: Record<string, { brackets: TaxBracket[]; standardDeduction: number; source: SourceProvenance; notes: string[] }> = {
  'us-fed': {
    source: PROVENANCE_SOURCES.IRS,
    standardDeduction: 15000, // 2025 Single standard deduction
    notes: ['Tax Year 2025 brackets indexed per IRS Rev. Proc. 2024-40', 'Standard deduction: $15,000 for Single filers'],
    brackets: [
      { min: 0, max: 11925, rate: 10 },
      { min: 11925, max: 48475, rate: 12 },
      { min: 48475, max: 103350, rate: 22 },
      { min: 103350, max: 197300, rate: 24 },
      { min: 197300, max: 250525, rate: 32 },
      { min: 250525, max: 626350, rate: 35 },
      { min: 626350, max: null, rate: 37 },
    ],
  },
  'ca-fed': {
    source: PROVENANCE_SOURCES.CRA,
    standardDeduction: 15705, // 2025 Basic Personal Amount
    notes: ['2025 Federal tax rates indexed at 2.7% CPI', 'Basic Personal Amount (BPA): $15,705'],
    brackets: [
      { min: 0, max: 57375, rate: 15 },
      { min: 57375, max: 114750, rate: 20.5 },
      { min: 114750, max: 177882, rate: 26 },
      { min: 177882, max: 253414, rate: 29 },
      { min: 253414, max: null, rate: 33 },
    ],
  },
  'in-new': {
    source: PROVENANCE_SOURCES.ITD_IN,
    standardDeduction: 75000, // FY 2025-26 standard deduction under New Regime
    notes: ['Union Budget revised Section 115BAC slabs', 'Standard deduction increased to ₹75,000 for salaried individuals', 'Tax rebate under Sec 87A for taxable income up to ₹7,00,000'],
    brackets: [
      { min: 0, max: 400000, rate: 0 },
      { min: 400000, max: 800000, rate: 5 },
      { min: 800000, max: 1200000, rate: 10 },
      { min: 1200000, max: 1600000, rate: 15 },
      { min: 1600000, max: 2000000, rate: 20 },
      { min: 2000000, max: 2400000, rate: 25 },
      { min: 2400000, max: null, rate: 30 },
    ],
  },
  'in-old': {
    source: PROVENANCE_SOURCES.ITD_IN,
    standardDeduction: 50000,
    notes: ['Old Tax Regime allowing Section 80C, 80D, HRA deductions', 'Standard deduction ₹50,000'],
    brackets: [
      { min: 0, max: 250000, rate: 0 },
      { min: 250000, max: 500000, rate: 5 },
      { min: 500000, max: 1000000, rate: 20 },
      { min: 1000000, max: null, rate: 30 },
    ],
  },
  'gb-eng': {
    source: PROVENANCE_SOURCES.HMRC,
    standardDeduction: 12570, // Personal allowance
    notes: ['2024/25 Tax Year', 'Standard Personal Allowance is £12,570 (reduces by £1 for every £2 over £100,000)'],
    brackets: [
      { min: 0, max: 12570, rate: 0 },
      { min: 12570, max: 50270, rate: 20 },
      { min: 50270, max: 125140, rate: 40 },
      { min: 125140, max: null, rate: 45 },
    ],
  },
  'au-fed': {
    source: PROVENANCE_SOURCES.ATO,
    standardDeduction: 0, // Tax-free threshold built into bracket
    notes: ['2024–25 Stage 3 revised individual tax rates', 'Tax-free threshold up to $18,200', 'Medicare levy of 2% may apply separately'],
    brackets: [
      { min: 0, max: 18200, rate: 0 },
      { min: 18200, max: 45000, rate: 16 },
      { min: 45000, max: 135000, rate: 30 },
      { min: 135000, max: 190000, rate: 37 },
      { min: 190000, max: null, rate: 45 },
    ],
  },
  'sg-res': {
    source: PROVENANCE_SOURCES.IRAS,
    standardDeduction: 0,
    notes: ['Progressive resident tax rates (YA 2024 onwards)'],
    brackets: [
      { min: 0, max: 20000, rate: 0 },
      { min: 20000, max: 30000, rate: 2 },
      { min: 30000, max: 40000, rate: 3.5 },
      { min: 40000, max: 80000, rate: 7 },
      { min: 80000, max: 120000, rate: 11.5 },
      { min: 120000, max: 160000, rate: 15 },
      { min: 160000, max: 200000, rate: 18 },
      { min: 200000, max: 240000, rate: 19 },
      { min: 240000, max: 280000, rate: 19.5 },
      { min: 280000, max: 320000, rate: 20 },
      { min: 320000, max: 500000, rate: 22 },
      { min: 500000, max: 1000000, rate: 23 },
      { min: 1000000, max: null, rate: 24 },
    ],
  },
};

export const INITIAL_VERSIONED_RULES: VersionedFinancialRule[] = [
  {
    id: 'rule-fed-funds-2025',
    ruleKey: 'US_FED_FUNDS_TARGET_UPPER',
    title: 'Federal Reserve Target Rate (Upper Bound)',
    category: 'INTEREST_RATE',
    countryCode: 'US',
    value: 4.50,
    previousValue: 4.75,
    unit: 'PERCENT',
    validFrom: '2025-01-29',
    source: PROVENANCE_SOURCES.FED,
    version: 4,
    changeSummary: 'FOMC reduced target range by 25 bps to support economic sustainability.',
    methodologyNotes: 'Directly impacts US prime lending rates and adjustable-rate mortgages.',
    createdAt: '2025-01-29T19:00:00Z',
  },
  {
    id: 'rule-boc-policy-2025',
    ruleKey: 'CA_BOC_OVERNIGHT_RATE',
    title: 'Bank of Canada Policy Interest Rate',
    category: 'INTEREST_RATE',
    countryCode: 'CA',
    value: 3.25,
    previousValue: 3.75,
    unit: 'PERCENT',
    validFrom: '2025-01-29',
    source: PROVENANCE_SOURCES.BOC,
    version: 5,
    changeSummary: 'BoC cut policy rate by 50 basis points.',
    methodologyNotes: 'Directly dictates 5-year variable mortgage discounts in Canadian chartered banks.',
    createdAt: '2025-01-29T15:00:00Z',
  },
  {
    id: 'rule-rbi-repo-2025',
    ruleKey: 'IN_RBI_REPO_RATE',
    title: 'RBI Policy Repo Rate',
    category: 'INTEREST_RATE',
    countryCode: 'IN',
    value: 6.50,
    previousValue: 6.50,
    unit: 'PERCENT',
    validFrom: '2025-02-07',
    source: PROVENANCE_SOURCES.RBI,
    version: 8,
    changeSummary: 'Monetary Policy Committee voted to maintain status quo at 6.50%.',
    methodologyNotes: 'External Benchmark Linked Lending Rates (EBLR) tied directly to this rate.',
    createdAt: '2025-02-07T06:00:00Z',
  },
  {
    id: 'rule-boe-rate-2025',
    ruleKey: 'GB_BOE_BASE_RATE',
    title: 'Bank of England Official Bank Rate',
    category: 'INTEREST_RATE',
    countryCode: 'GB',
    value: 4.75,
    previousValue: 5.00,
    unit: 'PERCENT',
    validFrom: '2025-02-06',
    source: PROVENANCE_SOURCES.BOE,
    version: 3,
    changeSummary: 'Monetary Policy Committee voted 8-1 to reduce Bank Rate by 0.25 percentage points.',
    methodologyNotes: 'Standard variable rate (SVR) tracker mortgages adjusted immediately.',
    createdAt: '2025-02-06T12:00:00Z',
  },
];

export const INITIAL_WHAT_CHANGED_EVENTS: WhatChangedEvent[] = [
  {
    id: 'wc-ca-boc-cut-2025',
    title: 'Bank of Canada Decreases Overnight Rate by 50 bps to 3.25%',
    category: 'RATE_CUT',
    countryCode: 'CA',
    jurisdictionName: 'Federal',
    effectiveDate: '2025-01-29',
    publishedDate: '2025-01-29',
    summary: 'The Bank of Canada lowered its target for the overnight rate to 3.25%, citing cooling inflation and labor market stabilization.',
    detailedAnalysis: 'Borrowers with adjustable-rate mortgages (ARM) or Home Equity Lines of Credit (HELOC) will see monthly interest charges decrease by approximately $31 per $100,000 borrowed balance.',
    impactScore: 'HIGH',
    affectedPersonas: ['Homeowners', 'Property Buyers', 'Variable Rate Borrowers', 'Commercial Real Estate Investors'],
    source: PROVENANCE_SOURCES.BOC,
    previousRuleValue: '3.75%',
    newRuleValue: '3.25%',
  },
  {
    id: 'wc-us-fed-cut-2025',
    title: 'Federal Reserve Cuts Benchmark Fed Funds Rate to 4.50%',
    category: 'RATE_CUT',
    countryCode: 'US',
    jurisdictionName: 'Federal',
    effectiveDate: '2025-01-29',
    publishedDate: '2025-01-29',
    summary: 'The Federal Open Market Committee (FOMC) decided to lower the target range for the federal funds rate by 25 basis points to 4.25%–4.50%.',
    detailedAnalysis: 'Prime rate adjustments will flow into credit card APRs and variable business loans within 1-2 billing cycles. High Yield Savings Accounts (HYSA) yields are expected to ease from 4.8% to ~4.4%.',
    impactScore: 'HIGH',
    affectedPersonas: ['Mortgage Refinancers', 'HYSA Savers', 'Credit Card Holders', 'Business Owners'],
    source: PROVENANCE_SOURCES.FED,
    previousRuleValue: '4.75%',
    newRuleValue: '4.50%',
  },
  {
    id: 'wc-in-tax-budget-2025',
    title: 'India Union Budget 2025 Revises Section 115BAC Slabs and Hikes Standard Deduction',
    category: 'TAX_REFORM',
    countryCode: 'IN',
    jurisdictionName: 'Central Government',
    effectiveDate: '2025-04-01',
    publishedDate: '2025-02-01',
    summary: 'Ministry of Finance enhanced the standard deduction to ₹75,000 for salaried taxpayers under the New Tax Regime, widening 5% and 10% tax brackets.',
    detailedAnalysis: 'Salaried employees earning ₹15,00,000 will save approximately ₹17,500 annually in net tax liability under the revised Section 115BAC structure.',
    impactScore: 'HIGH',
    affectedPersonas: ['Salaried Employees', 'Chartered Accountants', 'HR & Payroll Managers', 'Young Professionals'],
    source: PROVENANCE_SOURCES.ITD_IN,
    previousRuleValue: '₹50,000 Standard Deduction',
    newRuleValue: '₹75,000 Standard Deduction',
  },
  {
    id: 'wc-gb-boe-cut-2025',
    title: 'Bank of England Reduces Base Rate to 4.75%',
    category: 'RATE_CUT',
    countryCode: 'GB',
    jurisdictionName: 'UK Nationwide',
    effectiveDate: '2025-02-06',
    publishedDate: '2025-02-06',
    summary: 'The Bank of England Monetary Policy Committee voted to cut the Bank Rate by 25 basis points to 4.75%.',
    detailedAnalysis: 'Fixed-rate mortgage renewal quotes for 2-year and 5-year terms have improved by 15-20 bps across High Street lenders (Barclays, Nationwide, HSBC).',
    impactScore: 'MEDIUM',
    affectedPersonas: ['Mortgage Renewers', 'First-Time Buyers', 'Buy-To-Let Landlords'],
    source: PROVENANCE_SOURCES.BOE,
    previousRuleValue: '5.00%',
    newRuleValue: '4.75%',
  },
];
